---
name: Markdown

"on":
  workflow_call:

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prettier
        uses: creyD/prettier_action@v4.6
        with:
          dry: true
          prettier_options: "--check **/*.md"
