---
name: Rust

"on":
  push:
    paths:
      - "**.rs"
      - "**.toml"

jobs:
  lint:
    uses: ./.github/workflows/rust-lint.yml

  style:
    uses: ./.github/workflows/rust-style.yml

  test:
    uses: ./.github/workflows/rust-test.yml
